title: "Tree Segmentation with DINOv3"
description: "Unsupervised tree segmentation using DINOv3 Vision Transformers"
author: "Research Team"
email: "your-email@example.com"

# Build settings
markdown: kramdown
highlighter: rouge
# remote_theme: pages-themes/midnight@v0.2.0
remote_theme: pages-themes/hacker@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# GitHub Pages settings
baseurl: "/tree-seg-unsuper"
url: "https://luccahuguet.github.io"

# Navigation
header_pages:
  - index.md
  - methodology.md
  - models.md
  - complete_example.md
  - troubleshooting.md
  - parameter_comparison.md
  - analysis.md

# Collections
collections:
  experiments:
    output: true
    permalink: /:collection/:name/


# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/

# Site settings for academic presentation
academic:
  show_downloads: true
  github_repo: "tree-seg-unsuper"
  
# Custom variables
experiment_date: "2025"
model_version: "v3"
dino_variant: "DINOv3"
